<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>Lessenrooster (PHP+MySQL+jQM demo)</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar" class="ui-responsive">
            <ul>
                <li><a href="<?=$this->path('student/register') ?>">Registreren</a></li>
                <li><a href="#" class="ui-btn-active ui-state-persist">Aanmelden</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2>Meld je aan</h2>
        <form id="form-login" name="form-login" method="post" action="" data-ajax="false">
            <label for="email">E-mailadres</label>
            <input id="email" name="email" type="email" data-mini="true" value="">

            <label for="password">Wachtwoord</label>
            <input id="password" name="password" type="password" data-mini="true" value="">

            <input id="button-login" name="button-login" type="submit" value="Aanmelden" data-inline="true" data-theme="b">
        </form>
    </div>
<?php $this->partial('footer'); ?>
</section>
</body>
</html>