<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>Lessenrooster (PHP+MySQL+jQM demo)</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar" class="ui-responsive">
            <ul>
                <li><a href="#" class="ui-btn-active ui-state-persist">Registreren</a></li>
                <li><a href="<?=$this->path('student/login') ?>">Aanmelden</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2>Registreer je</h2>
        <form id="form-register" method="post" action="" data-ajax="false">
            <label for="givenname">Voornaam</label>
            <input id="givenname" name="givenname" type="text" data-mini="true" value="<?=@$_POST['givenname'] ?>">

            <label for="familyname">Familienaam</label>
            <input id="familyname" name="familyname" type="text" data-mini="true" value="<?=@$_POST['familyname'] ?>">

            <label for="email">E-mailadres</label>
            <input id="email" name="email" type="email" data-mini="true" value="<?=@$_POST['email'] ?>">

            <label for="password">Wachtwoord</label>
            <input id="password" name="password" type="password" data-mini="true" value="">

            <input id="button-register" name="button-register" type="submit" value="Registreren" data-inline="true" data-theme="b">
        </form>
    </div>
<?php $this->partial('footer'); ?>
</section>
</body>
</html>