<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <h1>Lessenrooster (PHP+MySQL+jQM demo)</h1>
    </header>
    <div data-role="content">
        <h2>Er is een fout gebeurd</h2>
        <pre><?php var_dump($this->exception) ?></pre>
    </div>
<?php $this->partial('footer'); ?>
</section>
</body>
</html>