<!DOCTYPE html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>jQuery Mobile met PHP demo</title>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
<link href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" rel="stylesheet" type="text/css">
<link href="<?=$this->path('assets/css/main.css') ?>" rel="stylesheet" type="text/css">
</head>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>jQuery Mobile met PHP demo</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar">
            <ul>
                <li><a href="#" class="ui-btn-active ui-state-persist">Registreren</a></li>
                <li><a href="<?=$this->path('student/login') ?>">Aanmelden</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <form id="form-register" method="post" action="" data-ajax="false">
            <label for="givenname">Voornaam</label>
            <input id="givenname" name="givenname" type="text" data-mini="true" value="<?=@$_POST['givenname'] ?>">

            <label for="familyname">Familienaam</label>
            <input id="familyname" name="familyname" type="text" data-mini="true" value="<?=@$_POST['familyname'] ?>">

            <label for="email">E-mailadres</label>
            <input id="email" name="email" type="email" data-mini="true" value="<?=@$_POST['email'] ?>">

            <label for="password">Wachtwoord</label>
            <input id="password" name="password" type="password" data-mini="true" value="">

            <input id="button-register" name="button-register" type="submit" value="Registreren" data-inline="true" data-theme="b">
        </form>
    </div>
    <footer data-role="footer" data-position="fixed">
        <p>Copyright © 2013 <a href="http://www.arteveldehs.be/">Artevelde University College Ghent</a></p>
    </footer>
</section>
</body>
</html>