<!DOCTYPE html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>jQuery Mobile met PHP demo</title>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
<link href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" rel="stylesheet" type="text/css">
<link href="<?=$this->path('assets/css/main.css') ?>" rel="stylesheet" type="text/css">
</head>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>jQuery Mobile met PHP demo</h1>
        <nav data-role="navbar">
            <ul>
<?php if ($this->hasIdentity): ?>
                <li><a href="<?=$this->path('calendar') ?>" >Agenda</a></li>
                <li><a href="<?=$this->path('student/logout') ?>" data-ajax="false">Afmelden</a></li>
<?php else: ?>
                <li><a href="<?=$this->path('student/register') ?>">Registreren</a></li>
                <li><a href="<?=$this->path('student/login') ?>">Aanmelden</a></li>
<?php endif ?>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2><img src="<?=$this->path('assets/img/logo_EN.png') ?>" alt="Artevelde University College Ghent"></h2>
    </div>
    <footer data-role="footer" data-position="fixed">
        <p>Copyright © 2013 <a href="http://www.arteveldehs.be/">Artevelde University College Ghent</a></p>
    </footer>
</section>
</body>
</html>