<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>Lessenrooster (PHP+MySQL+jQM demo)</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar" class="ui-responsive">
            <ul>
                <li><a href="<?=$this->path('calendar') ?>">Agenda</a></li>
                <li><a href="#" class="ui-btn-active ui-state-persist">Opleidingsonderdeel toevoegen</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2>Opleidingsonderdeel toevoegen</h2>
        <form id="form-schedule" name="form-schedule" action="" method="post" data-ajax="false">
            <label for="course" class="select">Opleidingsonderdeel</label>
            <select name="course" id="course" data-native-menu="false" data-icon="plus" data-iconpos="left">
                <option value="">Kies een opleidingsonderdeel</option>
<?php foreach ($this->courses as $course): ?>
                <option value="<?=$course->getId() ?>"><?=$course->getName() ?></option>
<?php endforeach; ?>
            </select>

            <label for="day" class="select">Dag</label>
            <select name="day" id="day" data-native-menu="false" data-icon="plus" data-iconpos="left">
                <option value="">Kies een dag</option>
<?php foreach ($this->days as $day): ?>
                <option value="<?=$day->getId() ?>"><?=ucfirst($day->getName()) ?></option>
<?php endforeach; ?>
            </select>

            <label for="timeslots" class="select">Lestijden</label>
            <select name="timeslots[]" id="timeslots" multiple="multiple" data-native-menu="false" data-icon="grid" data-iconpos="left" required="required">
                <option value="">Kies lestijden</option>
                <optgroup label="Ochtend">
<?php foreach ($this->timeslots as $timeslot): ?>
<?php   if ($timeslot->getStart() < '12:00') : ?>
                    <option value="<?=$timeslot->getId() ?>" data-day="<?=$timeslot->getDay()->getId() ?>"><?=$timeslot->getDay()->getName() ?> <?=$timeslot->getStart() ?> - <?=$timeslot->getEnd() ?></option>
<?php   endif; ?>
<?php endforeach; ?>
                </optgroup>
                <optgroup label="Namiddag">
<?php foreach ($this->timeslots as $timeslot): ?>
<?php   if ('12:00' < $timeslot->getStart()  && $timeslot->getStart() < '17:30') : ?>
                    <option value="<?=$timeslot->getId() ?>" data-day="<?=$timeslot->getDay()->getId() ?>"><?=$timeslot->getDay()->getName() ?> <?=$timeslot->getStart() ?> - <?=$timeslot->getEnd() ?></option>
<?php   endif; ?>
<?php endforeach; ?>
                </optgroup>
                <optgroup label="Avond">
<?php foreach ($this->timeslots as $timeslot): ?>
<?php   if ('17:30' <= $timeslot->getStart()) : ?>
                    <option value="<?=$timeslot->getId() ?>" data-day="<?=$timeslot->getDay()->getId() ?>"><?=$timeslot->getDay()->getName() ?> <?=$timeslot->getStart() ?> - <?=$timeslot->getEnd() ?></option>
<?php   endif; ?>
<?php endforeach; ?>
                </optgroup>
            </select>

            <label for="room" class="select">Lokaal</label>
            <select name="room" id="room" data-native-menu="false" data-icon="plus" data-iconpos="left"  required="required">
                <option value="" disabled>Kies een lokaal</option>
<?php foreach ($this->rooms as $room): ?>
                <option value="<?=$room->getId() ?>"><?=$room->getName() ?></option>
<?php endforeach; ?>
            </select>

            <label for="lecturers" class="select">Docenten</label>
            <select name="lecturers[]" id="lecturers" multiple="multiple" data-native-menu="false" data-icon="plus" data-iconpos="left"  required="required">
                <option>Kies docenten</option>
<?php foreach ($this->lecturers as $lecturer): ?>
                <option value="<?=$lecturer->getId() ?>"><?=$lecturer->getGivenname() ?> <?=$lecturer->getFamilyname() ?></option>
<?php endforeach; ?>
            </select>

            <input type="submit" name="button-schedule" value="Opleidingsonderdeel opslaan" data-theme="b">
        </form>
    </div>
<?php $this->partial('footer'); ?>
</section>
</body>
</html>