<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>Lessenrooster (PHP+MySQL+jQM demo)</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar" class="ui-responsive">
            <ul>
                <li><a href="#" class="ui-btn-active ui-state-persist">Agenda</a></li>
                <li><a href="<?=$this->path('calendar/add') ?>" data-ajax="false">Opleidingsonderdeel toevoegen</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">

        <h2><a href="#panel-today" data-role="button" data-icon="bars" data-corners="false" data-mini="true" data-inline="true" style="float:left">Vandaag</a> Agenda voor <?=$this->student->getGivenname() ?> <?=$this->student->getFamilyname() ?></h2>
        <ul id="this-week" data-role="listview" data-inset="true" data-theme="d" data-divider-theme="d">
<?php foreach ($this->scheduleThisWeek as $schedule): ?>
<?php
    if (isset($day)) {
        $dayNew = ucfirst($schedule->getTimeslot()->getDay()->getName());
        if ($day !== $dayNew) {
            $day = $dayNew;
?>
            <li data-role="list-divider"><?=$day ?></li>
<?php
        }
    } else {
        $day = ucfirst($schedule->getTimeslot()->getDay()->getName());
?>
            <li data-role="list-divider"><?=$day ?></li>
<?php

    }
?>
            <li data-student-id="<?=$schedule->getStudent()->getId() ?>" data-timeslot-id="<?=$schedule->getTimeslot()->getId() ?>">
                <a>
                    <h3><?=$schedule->getCourse()->getName() ?></h3>
                    <p><?php foreach ($schedule->getCourse()->getLecturers() as $key => $lecturer) echo (0 < $key ? ', ' : '') , $lecturer->getGivenname(), ' ' , $lecturer->getFamilyname(); ?></p>

                    <span class="ui-li-count"><?=$schedule->getRoom()->getName() ?><br><?=$schedule->getTimeslot()->getStart() ?> - <?=$schedule->getTimeslot()->getEnd() ?></span>
                </a>
                <a href="#" data-icon="delete"></a>
            </li>
<?php endforeach ?>
        </ul>
    </div>

<?php $this->partial('footer'); ?>

    <div data-role="panel" data-display="overlay" id="panel-today">
        <ul data-role="listview">
            <li data-role="list-divider">Vandaag</li>
<?php foreach ($this->scheduleToday as $schedule): ?>
            <li>
                <h3><?=$schedule->getCourse()->getName() ?></h3>
                <p><?php foreach ($schedule->getCourse()->getLecturers() as $key => $lecturer) echo (0 < $key ? '<br>' : '') , $lecturer->getGivenname(), ' ' , $lecturer->getFamilyname(); ?></p>
                <p class="ui-li-count"><?=$schedule->getRoom()->getName() ?><br><?=$schedule->getTimeslot()->getStart() ?> - <?=$schedule->getTimeslot()->getEnd() ?></p>
            </li>
<?php endforeach ?>
        </ul>
    </div>
</section>

</body>
</html>