<!DOCTYPE html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>jQuery Mobile met PHP demo</title>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
<script src="<?=$this->path('assets/js/calendar.js') ?>"></script>
<link href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" rel="stylesheet" type="text/css">
<link href="<?=$this->path('assets/css/main.css') ?>" rel="stylesheet" type="text/css">
</head>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>jQuery Mobile met PHP demo</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar">
            <ul>
                <li><a href="<?=$this->path('calendar') ?>">Agenda</a></li>
                <li><a href="#" class="ui-btn-active ui-state-persist">Opleidingsonderdeel toevoegen</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h1>Opleidingsonderdeel toevoegen</h1>
        <form id="form-schedule" name="form-schedule" action="" method="post" data-ajax="false">
            <label for="course" class="select">Opleidingsonderdeel</label>
            <select name="course" id="course" data-native-menu="false" data-icon="plus" data-iconpos="left">
                <option>Kies een opleidingsonderdeel</option>
<?php foreach ($this->courses as $course): ?>
                <option value="<?=$course->getId() ?>"><?=$course->getName() ?></option>
<?php endforeach; ?>
            </select>

            <label for="day" class="select">Dag</label>
            <select name="day" id="day" data-native-menu="false" data-icon="plus" data-iconpos="left">
                <option>Kies een dag</option>
<?php foreach ($this->days as $day): ?>
                <option value="<?=$day->getId() ?>"><?=ucfirst($day->getName()) ?></option>
<?php endforeach; ?>
            </select>

            <label for="timeslots" class="select">Lestijd</label>
            <select name="timeslots[]" id="timeslots" multiple="multiple" data-native-menu="false" data-icon="grid" data-iconpos="left">
                <option>Kies lestijden</option>
                <optgroup label="Ochtend">
<?php foreach ($this->timeslots as $timeslot): ?>
<?php   if ($timeslot->getStart() < '12:00') : ?>
                    <option value="<?=$timeslot->getId() ?>" data-day="<?=$timeslot->getDay()->getId() ?>"><?=$timeslot->getDay()->getName() ?> <?=$timeslot->getStart() ?> - <?=$timeslot->getEnd() ?></option>
<?php   endif; ?>
<?php endforeach; ?>
                </optgroup>
                <optgroup label="Namiddag">
<?php foreach ($this->timeslots as $timeslot): ?>
<?php   if ('12:00' < $timeslot->getStart()  && $timeslot->getStart() < '17:30') : ?>
                    <option value="<?=$timeslot->getId() ?>" data-day="<?=$timeslot->getDay()->getId() ?>"><?=$timeslot->getDay()->getName() ?> <?=$timeslot->getStart() ?> - <?=$timeslot->getEnd() ?></option>
<?php   endif; ?>
<?php endforeach; ?>
                </optgroup>
                <optgroup label="Avond">
<?php foreach ($this->timeslots as $timeslot): ?>
<?php   if ('17:30' <= $timeslot->getStart()) : ?>
                    <option value="<?=$timeslot->getId() ?>" data-day="<?=$timeslot->getDay()->getId() ?>"><?=$timeslot->getDay()->getName() ?> <?=$timeslot->getStart() ?> - <?=$timeslot->getEnd() ?></option>
<?php   endif; ?>
<?php endforeach; ?>
                </optgroup>
            </select>

            <label for="room" class="select">Lokaal</label>
            <select name="room" id="room" data-native-menu="false" data-icon="plus" data-iconpos="left">
                <option>Kies een lokaal</option>
<?php foreach ($this->rooms as $room): ?>
                <option value="<?=$room->getId() ?>"><?=$room->getName() ?></option>
<?php endforeach; ?>
            </select>

            <label for="lecturers" class="select">Docent</label>
            <select name="lecturers[]" id="lecturer" multiple="multiple" data-native-menu="false" data-icon="plus" data-iconpos="left">
                <option>Kies docenten</option>
<?php foreach ($this->lecturers as $lecturer): ?>
                <option value="<?=$lecturer->getId() ?>"><?=$lecturer->getGivenname() ?> <?=$lecturer->getFamilyname() ?></option>
<?php endforeach; ?>
            </select>

            <input type="submit" name="button-schedule" value="Opleidingsonderdeel opslaan" data-theme="b">
        </form>
    </div>
    <footer data-role="footer" data-position="fixed">
        <p>Copyright © 2013 <a href="http://www.arteveldehs.be/">Artevelde University College Ghent</a></p>
    </footer>
</section>
</body>
</html>