<!DOCTYPE html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>jQuery Mobile met PHP demo</title>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
<script src="<?=$this->path('assets/js/calendar.js') ?>"></script>
<link href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" rel="stylesheet" type="text/css">
<link href="<?=$this->path('assets/css/main.css') ?>" rel="stylesheet" type="text/css">
</head>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>jQuery Mobile met PHP demo</h1>
        <a href="<?=$this->path() ?>" data-icon="home" data-iconpos="notext">Start</a>
        <nav data-role="navbar">
            <ul>
                <li><a href="#" class="ui-btn-active ui-state-persist">Agenda</a></li>
                <li><a href="<?=$this->path('calendar/add') ?>" data-ajax="false">Opleidingsonderdeel toevoegen</a></li>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2>Agenda voor <?=$this->student->getGivenname() ?> <?=$this->student->getFamilyname() ?></h2>
        <h3>Vandaag</h3>
        <ul>
<?php foreach ($this->scheduleToday as $schedule): ?>
            <li><?=$schedule->getTimeslot()->getStart() ?> - <?=$schedule->getTimeslot()->getEnd() ?> in <?=$schedule->getRoom()->getName() ?>: <br><strong><?=$schedule->getCourse()->getName() ?></strong> <?php foreach ($schedule->getCourse()->getLecturers() as $lecturer) echo '<br>', $lecturer->getGivenname(), ' ' , $lecturer->getFamilyname(); ?></li>
<?php endforeach ?>
        </ul>
        <h3>Deze week</h3>
        <ul>
<?php foreach ($this->scheduleThisWeek as $schedule): ?>
            <li><?=ucfirst($schedule->getTimeslot()->getDay()->getName() ) ?> <?=$schedule->getTimeslot()->getStart() ?> - <?=$schedule->getTimeslot()->getEnd() ?> in <?=$schedule->getRoom()->getName() ?>: <br><strong><?=$schedule->getCourse()->getName() ?></strong> <?php foreach ($schedule->getCourse()->getLecturers() as $lecturer) echo '<br>' , $lecturer->getGivenname(), ' ' , $lecturer->getFamilyname(); ?></li>
<?php endforeach ?>
        </ul>
    </div>
    <footer data-role="footer" data-position="fixed">
        <p>Copyright © 2013 <a href="http://www.arteveldehs.be/">Artevelde University College Ghent</a></p>
    </footer>
</section>
</body>
</html>