<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
    <header data-role="header" data-position="fixed">
        <h1>jQuery Mobile met PHP demo</h1>
        <nav data-role="navbar" class="ui-responsive">
            <ul>
<?php if ($this->hasIdentity): ?>
                <li><a href="<?=$this->path('calendar') ?>" >Agenda</a></li>
                <li><a href="<?=$this->path('student/logout') ?>" data-ajax="false">Afmelden</a></li>
<?php else: ?>
                <li><a href="<?=$this->path('student/register') ?>">Registreren</a></li>
                <li><a href="<?=$this->path('student/login') ?>">Aanmelden</a></li>
<?php endif; ?>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2><img src="<?=$this->path('assets/img/logo_EN.png') ?>" alt="Artevelde University College Ghent"></h2>
    </div>
<?php $this->partial('footer'); ?>
</section>
</body>
</html>