<!DOCTYPE html>
<html lang="nl">
<?php $this->partial('head'); ?>
<body>
<section data-role="page">
<!--[if lt IE 10]>
    <div>You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</div>
<![endif]-->
    <header data-role="header" data-position="fixed">
        <h1>Lessenrooster (PHP+MySQL+jQM demo)</h1>
        <nav data-role="navbar" class="ui-responsive">
            <ul>
<?php if ($this->hasIdentity): ?>
                <li><a href="<?=$this->path('calendar') ?>" >Agenda</a></li>
                <li><a href="<?=$this->path('student/logout') ?>" data-ajax="false">Afmelden</a></li>
<?php else: ?>
                <li><a href="<?=$this->path('student/register') ?>">Registreren</a></li>
                <li><a href="<?=$this->path('student/login') ?>">Aanmelden</a></li>
<?php endif; ?>
            </ul>
        </nav>
    </header>
    <div data-role="content">
        <h2><img id="ahs-logo" src="<?=$this->path('assets/img/logo_EN.png') ?>" alt="Artevelde University College Ghent"></h2>
    </div>
<?php $this->partial('footer'); ?>
</section>
</body>
</html>