<head>
    <meta charset="utf-8">
    <title>jQuery Mobile</title>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
    <link href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" rel="stylesheet" type="text/css">
    <link href="<?=$this->path('assets/css/main.css') ?>" rel="stylesheet" type="text/css">
</head>