<head>
    <meta charset="utf-8">
    <title>jQuery Mobile</title>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="https://raw.github.com/wycats/handlebars.js/1.0.0-rc.3/dist/handlebars.runtime.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js"></script>
<?php foreach ($this->headScripts as $script) echo $script; ?>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css">
    <link rel="stylesheet" href="<?=$this->path('assets/css/main.css') ?>">
<?php foreach ($this->headStylesheets as $stylesheet) echo $stylesheet; ?>
</head>