<head>
    <meta charset="utf-8">
    <title>Lessenrooster</title>
    <link href="<?=$this->path('assets/img/favicon.ico') ?>" rel="shortcut icon" type="image/x-icon">
    <link href="<?=$this->path('assets/img/touch-icon-iphone.png') ?>" rel="apple-touch-icon" sizes="57x57">
    <link href="<?=$this->path('assets/img/touch-icon-ipad.png') ?>" rel="apple-touch-icon" sizes="72x72">
    <link href="<?=$this->path('assets/img/touch-icon-iphone-retina.png') ?>" rel="apple-touch-icon" sizes="114x114">
    <link href="<?=$this->path('assets/img/touch-icon-ipad-retina.png') ?>" rel="apple-touch-icon" sizes="144x144">
    <link href="<?=$this->path('humans.txt') ?>" rel="author" >
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="https://raw.github.com/wycats/handlebars.js/1.0.0-rc.3/dist/handlebars.runtime.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js"></script>
<?php foreach ($this->headScripts as $script) echo $script; ?>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css">
    <link rel="stylesheet" href="<?=$this->path('assets/css/main.css') ?>">
<?php foreach ($this->headStylesheets as $stylesheet) echo $stylesheet; ?>
</head>